version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/aws-devops-pgp1
hooks:
  BeforeInstall:
    - location: scripts/boot.sh
      timeout: 300
      runas: root

  BeforeAllowTraffic:
    - location: scripts/start.sh
      timeout: 300
      runas: root
