custombucket = "aws-devops-pgp-s3bucket"
table = "intellipaat"
databasehost = "intellipaat.cnocegoqwzg9.us-east-1.rds.amazonaws.com"
duser = "intellipaat"
dpass = "intellipaat123"
s3database = "intellipaat"
kapp = "http://35.171.23.186:30007/"
