custombucket = "aws-devops-pgp-s3bucket"
table = "intellipaat"
databasehost = "intellipaat.cnocegoqwzg9.us-east-1.rds.amazonaws.com"
duser = "intellipaat"
dpass = "intellipaat123"
s3database = "intellipaat"
kapp = "http://18.212.102.11:30007/"
