custombucket = "rds--source"
table = "intellipaat"
databasehost = "database-1.czwalaijacr8.us-east-1.rds.amazonaws.com"
duser = "intellipaat"
dpass = "intellipaat123"
s3database = "intellipaat"
kapp = "http://10.0.2.233:30007/"
